# ML-10 — Content Action Playbook

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/prithvirajr203-pixel/Notebook-FlyRank/blob/main/work/notebooks/w07_action_playbook.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Ranked actions + reason codes

*The queue: what to do first, and why, in words a human trusts.*

In [6]:
import pandas as pd

ranked_actions = pd.DataFrame([
    {
        "rank": 1,
        "action": "Refresh content showing performance decay",
        "reason_code": "DECAY",
        "evidence": "Observed decline in performance over time",
        "priority": "High",
        "human_review_required": True
    },
    {
        "rank": 2,
        "action": "Review pages with high impressions but weak CTR",
        "reason_code": "LOW_CTR",
        "evidence": "Visibility is present but engagement is comparatively weak",
        "priority": "High",
        "human_review_required": True
    },
    {
        "rank": 3,
        "action": "Investigate pages with measurable performance drops",
        "reason_code": "PERFORMANCE_DROP",
        "evidence": "Recent performance is weaker than the available baseline",
        "priority": "Medium",
        "human_review_required": True
    },
    {
        "rank": 4,
        "action": "Review pages with improvement opportunity",
        "reason_code": "OPPORTUNITY",
        "evidence": "Model signals indicate pages worth further investigation",
        "priority": "Medium",
        "human_review_required": True
    }
])

display(ranked_actions)

,rank,action,reason_code,evidence,priority,human_review_required
0,1,Refresh content showing performance decay,DECAY,Observed decline in performance over time,High,True
1,2,Review pages with high impressions but weak CTR,LOW_CTR,Visibility is present but engagement is compar...,High,True
2,3,Investigate pages with measurable performance ...,PERFORMANCE_DROP,Recent performance is weaker than the availabl...,Medium,True
3,4,Review pages with improvement opportunity,OPPORTUNITY,Model signals indicate pages worth further inv...,Medium,True

## 2. Intended use and limits

*Who uses this, for what — and where it stops being valid.*

In [7]:
intended_use = {
    "purpose": "Prioritize content for human investigation",
    "users": "Content strategists and SEO analysts",
    "use_type": "Decision support",
    "automatic_changes": False,
    "causal_claims": False,
    "guaranteed_ranking_improvement": False,
    "production_use": False,
    "limitation": "Recommendations depend on the available FlyRank data and validation design",
    "generalization": "Results may not generalize to unseen clients, future search behavior, or different content types"
}

for key, value in intended_use.items():
    print(f"{key}: {value}")

purpose: Prioritize content for human investigation
users: Content strategists and SEO analysts
use_type: Decision support
automatic_changes: False
causal_claims: False
guaranteed_ranking_improvement: False
production_use: False
limitation: Recommendations depend on the available FlyRank data and validation design
generalization: Results may not generalize to unseen clients, future search behavior, or different content types

## 3. Human review + the no-go list

*What a person must check before acting. What should never be automated.*

In [8]:
import pandas as pd

human_review_rules = pd.DataFrame([
    ["Content accuracy", "Check that the recommended page is accurate and up to date"],
    ["Search intent", "Confirm that the recommendation matches the page's search intent"],
    ["Business context", "Check editorial, brand, and business constraints"],
    ["Evidence", "Verify the observed signal before taking action"],
    ["Alternative causes", "Check whether another factor explains the observed change"]
], columns=["review_area", "required_check"])

no_go_list = pd.DataFrame([
    ["Automatic content publishing", False],
    ["Automatic page deletion", False],
    ["Automatic redirects", False],
    ["Automatic metadata changes", False],
    ["Guaranteed ranking claims", False],
    ["Using one model score as the final decision", False],
    ["Replacing human editorial judgment", False]
], columns=["action", "automate"])

print("HUMAN REVIEW RULES")
display(human_review_rules)

print("\nNO-GO LIST")
display(no_go_list)

HUMAN REVIEW RULES

          review_area                                     required_check
0    Content accuracy  Check that the recommended page is accurate an...
1       Search intent  Confirm that the recommendation matches the pa...
2    Business context   Check editorial, brand, and business constraints
3            Evidence    Verify the observed signal before taking action
4  Alternative causes  Check whether another factor explains the obse...

NO-GO LIST

                                        action  automate
0                 Automatic content publishing     False
1                      Automatic page deletion     False
2                          Automatic redirects     False
3                   Automatic metadata changes     False
4                    Guaranteed ranking claims     False
5  Using one model score as the final decision     False
6           Replacing human editorial judgment     False

## 4. Monitoring / retrain triggers

*What would tell you the recommendations went stale?*

In [9]:
import pandas as pd

monitoring_triggers = pd.DataFrame([
    {
        "signal": "Model performance",
        "trigger": "Sustained degradation on new observations",
        "response": "Revalidate or retrain the model"
    },
    {
        "signal": "Feature distribution",
        "trigger": "Material change in important feature distributions",
        "response": "Investigate data drift and revalidate"
    },
    {
        "signal": "Human agreement",
        "trigger": "Increasing disagreement between recommendations and human review",
        "response": "Review assumptions and recommendation rules"
    },
    {
        "signal": "Content type",
        "trigger": "New content types not represented in the original data",
        "response": "Assess applicability before using recommendations"
    },
    {
        "signal": "Outcome relationship",
        "trigger": "Observed relationship between features and outcomes changes materially",
        "response": "Reassess and potentially retrain the model"
    }
])

display(monitoring_triggers)

,signal,trigger,response
0,Model performance,Sustained degradation on new observations,Revalidate or retrain the model
1,Feature distribution,Material change in important feature distribut...,Investigate data drift and revalidate
2,Human agreement,Increasing disagreement between recommendation...,Review assumptions and recommendation rules
3,Content type,New content types not represented in the origi...,Assess applicability before using recommendations
4,Outcome relationship,Observed relationship between features and out...,Reassess and potentially retrain the model

## 5. Exports for the paper

*Write the queue (and any figures you want to reuse) to work/outputs/ — your paper builds on these files.*

In [10]:
from pathlib import Path

# Create the output directory if it does not already exist
output_dir = Path("work/outputs")
output_dir.mkdir(parents=True, exist_ok=True)

# Export the ranked action queue
queue_path = output_dir / "ranked_action_queue.csv"

ranked_actions.to_csv(queue_path, index=False)

# Verify the export
print("Export completed successfully.")
print(f"File: {queue_path}")
print(f"Rows exported: {len(ranked_actions)}")

# Read the exported file back and verify it
exported_queue = pd.read_csv(queue_path)

display(exported_queue)

assert queue_path.exists(), "Export file was not created."
assert len(exported_queue) == len(ranked_actions), "Export row count does not match."
assert "reason_code" in exported_queue.columns, "Reason code column is missing."

print("\nExport verification: PASS")

Export completed successfully.
File: work/outputs/ranked_action_queue.csv
Rows exported: 4

,rank,action,reason_code,evidence,priority,human_review_required
0,1,Refresh content showing performance decay,DECAY,Observed decline in performance over time,High,True
1,2,Review pages with high impressions but weak CTR,LOW_CTR,Visibility is present but engagement is compar...,High,True
2,3,Investigate pages with measurable performance ...,PERFORMANCE_DROP,Recent performance is weaker than the availabl...,Medium,True
3,4,Review pages with improvement opportunity,OPPORTUNITY,Model signals indicate pages worth further inv...,Medium,True

Export verification: PASS

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.